### ISSUE TITLE
Updating code architecture

### ISSUE THREAD

**Issue by colemanw** [systopia/de.systopia.eck#11]
CiviCRM's recommended coding practices have changed in the past few years, and this extension was written with a few outdated conventions which would be good to update.

- **Don't use APIv3:** Most new extensions have minimal or no support for APIv3. The newest ones, Afform and SearchKit, do not provide any APIv3 support at all. According to the [Developer Docs](https://docs.civicrm.org/dev/en/latest/api/#api-versions), "v4 is recommended for all new projects". Since this is a new extension, any code needing to access `EckEntity` APIs would necessarily be a new project. Dropping support for v3 now would reduce maintenance costs for this extension and prevent integrators from adding technical debt by requiring them to use v4.
- **Use BAO::writeRecord() and hooks:** We are moving away from writing `create()` and `del()` functions in BAOs, instead allowing them to inherit `writeRecord()` and `deleteRecord()` from `CRM_Core_DAO`. Any pre/post processing belongs in hooks.
- **Keep business logic out of the form layer:** Per the above point, all business logic related to creating, updating and deleting records should be done by the BAO, preferably using hooks. Form post process functions should ideally do no processing at all, and hand it over to the BAO or API. In this extension, a mistake was made by calling `CRM_Eck_BAO_EckEntityType::ensureEntityType()` from `CRM_Eck_Form_EntityType::postProcess` - this causes the form to work correctly but the API to be broken.

**Comment by jensschuppe** [comment]
> * **Use BAO::writeRecord() and hooks:** We are moving away from writing `create()` and `del()` functions in BAOs, instead allowing them to inherit `writeRecord()` and `deleteRecord()` from `CRM_Core_DAO`. Any pre/post processing belongs in hooks.

So this code https://github.com/systopia/de.systopia.eck/pull/8/files#r811726578 belongs in a hook as well, I guess ...

**Comment by colemanw** [comment]
This issue is fixed by #14 and #13

**Comment by jensschuppe** [comment]
Well, partly fixed, there's still some logic in the forms and also some APIv3 calls in the pages. I'll leave the issue open as a reminder for that.

**Comment by jensschuppe** [comment]
There's still some validation logic in the forms that might go into the API, but let's track that separately.
