### ISSUE TITLE
Create/update/delete failing due to blank table name

### ISSUE THREAD

**Issue by angusfretwell** [systopia/de.systopia.eck#111]
With the latest version of ECK on CiviCRM 5.69.4, create/update/delete actions are failing due to `table_name` being blank in the generated SQL. I think this might be related to #104, but I haven't done much digging yet.

This is the error I get when attempting to create an ECK record via the API4 explorer:

```json
{
    "error_code": 0,
    "error_message": "DB Error: unknown error",
    "debug": {
        "info": "INSERT INTO `` (`title` , `subtype` , `created_id` , `modified_id` , `created_date` , `modified_date` ) VALUES ('test 1234' , '2' ,  2 ,  2 ,  20240205083213 ,  20240205083213 )  [nativecode=1103 ** Incorrect table name '']",
        "db_error": "unknown error",
        "sql": [
            "INSERT INTO `` (`title` , `subtype` , `created_id` , `modified_id` , `created_date` , `modified_date` ) VALUES ('test 1234' , '2' ,  2 ,  2 ,  20240205083213 ,  20240205083213 )  [nativecode=1103 ** Incorrect table name '']"
        ]   
    }
}
```

I'll test on a fresh CiviCRM install and make sure this is reproducible.

**Comment by angusfretwell** [comment]
Confirmed I get a similar error on a fresh install (CiviCRM 5.69.4, Drupal 10, PHP 8.2):

{
    "error_code": 1103,
    "error_message": "Incorrect table name ''",
    "status": 500
}

I'm using @colemanw's branch which fixes the `getLinks` issue (https://github.com/colemanw/de.systopia.eck/tree/getLinksPlaceholder)

**Comment by jensschuppe** [comment]
This doesn't seem to be fixed by #110.

**Comment by jensschuppe** [comment]
@angusfretwell Could you see whether #112 fixes your issue?

**Comment by angusfretwell** [comment]
Works like a charm, thanks @jensschuppe
