### ISSUE TITLE
Allowing EckEntityType to be renamed

### ISSUE THREAD

**Issue by colemanw** [systopia/de.systopia.eck#12]
I noticed the `\CRM_Eck_BAO_EckEntityType::ensureEntityType()` function takes a lot of trouble to handle the possibility of renaming an entity type. Not just changing the label (which is easy) but actually changing the entity name and even the sql table name!

Note the precedent in CiviCRM core:
- Custom Groups and Custom Fields cannot be renamed
- Activity types cannot be renamed
- Contact types cannot be renamed
- Relationship types cannot be renamed
- Case types cannot be renamed

IMO renaming entity types should not be allowed, and the API should throw an exception if attempted. If it is allowed, very thorough unit test coverage should be added, checking complete data integrity after a rename operation.

**Comment by jensschuppe** [comment]
Valid point with Core's current behavior, although that's something I never really warmed up to and thus tried to keep names, labels and table names consistent. But I think you're right, let's not allow changing entity type names.
