### ISSUE TITLE
SearchKit Toolbar links for creating new entities of different subtypes

### ISSUE THREAD

**Issue by jensschuppe** [systopia/de.systopia.eck#120]
With the new *SearchKit* Toolbar, a link for adding new ECK entities can be added to a *SearchKit* display. However, since the path of the *Add* form for ECK entities is dependent on the subtype, there would have to be as many *Add* links as there are subtypes for the entity type. The link that is being created with the current version includes the subtype ID of the first search result.

The ECK listings the extension is being shipped with does that in an Afform with a custom template for the dropdown button.

Is it possible to provide multiple such links for an entity type to be used in the *SearchKit* Toolbar in a generic way?

Ping @colemanw

**Comment by colemanw** [comment]
Hi @jensschuppe maybe I am misunderstanding you but

> there would have to be as many Add links as there are subtypes for the entity type

That's exactly what it does. This code:

https://github.com/systopia/de.systopia.eck/blob/1ad91f60ad28085788bf1811b64ef673f711170d/Civi/Api4/Service/Links/ECKLinksProvider.php#L26-L31

Results in a dropdown like this:

![image](https://github.com/systopia/de.systopia.eck/assets/2874912/52c71d35-e852-4442-8787-b4f926d10c5f)

**Comment by jensschuppe** [comment]
Thanks for clarifying that there's one link to select in the *SearchKit* admin UI that expands into multiple ones during rendering - I wasn't aware it works like that.

With a simple search, this indeed works, while in some others we have configured it doesn't. Seems we'll have to find out what makes them different …

**Comment by jensschuppe** [comment]
Used the wrong version, sorry for crying wolf … :wolf:

**Comment by colemanw** [comment]
Bah 🐑
