### ISSUE TITLE
Error when Saving a new Entity

### ISSUE THREAD

**Issue by cwerstuik** [systopia/de.systopia.eck#132]
When I save a new entity through the SearchKit UI that's auto generated by ECK, it says it saves, but then nothing happens.

When I view the logs, all I get is:

`[debug] Silently ignoring exception in Afform processGenericEntity call: DB_DataObject Error: insert:No table definition for civicrm_eck_keys`

Debugging is turned on, but there's no backtrace

I'm running CiviCRM 5.73.2
ECK 1.0-beta10

**Comment by cwerstuik** [comment]
I found a backtrace when I use the API4 UI

  "backtrace": "#0 /bitnami/wordpress/wp-content/plugins/civicrm/civicrm/vendor/pear/pear-core-minimal/src/PEAR.php(945): CRM_Core_Error::exceptionHandler()
#1 /bitnami/wordpress/wp-content/plugins/civicrm/civicrm/packages/DB/DataObject/Error.php(44): PEAR_Error->__construct()
#2 /bitnami/wordpress/wp-content/plugins/civicrm/civicrm/vendor/pear/pear-core-minimal/src/PEAR.php(577): DB_DataObject_Error->__construct()
#3 /bitnami/wordpress/wp-content/plugins/civicrm/civicrm/vendor/pear/pear-core-minimal/src/PEAR.php(223): PEAR::_raiseError()
#4 /bitnami/wordpress/wp-content/plugins/civicrm/civicrm/packages/DB/DataObject.php(4829): PEAR->__call()
#5 /bitnami/wordpress/wp-content/plugins/civicrm/civicrm/packages/DB/DataObject.php(1081): DB_DataObject->raiseError()
#6 /bitnami/wordpress/wp-content/plugins/civicrm/civicrm/CRM/Core/DAO.php(747): DB_DataObject->insert()
#7 /bitnami/wordpress/wp-content/uploads/civicrm/ext/de.systopia.eck-1.0-beta10/CRM/Eck/DAO/Entity.php(271): CRM_Core_DAO->save()
#8 /bitnami/wordpress/wp-content/plugins/civicrm/civicrm/CRM/Core/DAO.php(1084): CRM_Eck_DAO_Entity::writeRecord()
#9 /bitnami/wordpress/wp-content/uploads/civicrm/ext/de.systopia.eck-1.0-beta10/Civi/Api4/EckSaveTrait.php(35): CRM_Core_DAO::writeRecords()
#10 /bitnami/wordpress/wp-content/plugins/civicrm/civicrm/Civi/Api4/Generic/Traits/DAOActionTrait.php(139): Civi\\Api4\\EckDAOCreateAction->write()
#11 /bitnami/wordpress/wp-content/plugins/civicrm/civicrm/Civi/Api4/Generic/DAOCreateAction.php(35): Civi\\Api4\\Generic\\DAOCreateAction->writeObjects()
#12 /bitnami/wordpress/wp-content/plugins/civicrm/civicrm/Civi/Api4/Provider/ActionObjectProvider.php(70): Civi\\Api4\\Generic\\DAOCreateAction->_run()
#13 /bitnami/wordpress/wp-content/plugins/civicrm/civicrm/Civi/API/Kernel.php(156): Civi\\Api4\\Provider\\ActionObjectProvider->invoke()
#14 /bitnami/wordpress/wp-content/plugins/civicrm/civicrm/Civi/Api4/Generic/AbstractAction.php(256): Civi\\API\\Kernel->runRequest()
#15 /bitnami/wordpress/wp-content/plugins/civicrm/civicrm/api/api.php(91): Civi\\Api4\\Generic\\AbstractAction->execute()
#16 /bitnami/wordpress/wp-content/plugins/civicrm/civicrm/CRM/Api4/Page/AJAX.php(116): civicrm_api4()
#17 /bitnami/wordpress/wp-content/plugins/civicrm/civicrm/CRM/Api4/Page/AJAX.php(55): CRM_Api4_Page_AJAX->execute()
#18 /bitnami/wordpress/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(325): CRM_Api4_Page_AJAX->run()
#19 /bitnami/wordpress/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(69): CRM_Core_Invoke::runItem()
#20 /bitnami/wordpress/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(36): CRM_Core_Invoke::_invoke()
#21 /bitnami/wordpress/wp-content/plugins/civicrm/civicrm.php(1231): CRM_Core_Invoke::invoke()
#22 /var/www/html/wp-includes/class-wp-hook.php(324): CiviCRM_For_WordPress->invoke()
#23 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#24 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action()
#25 /var/www/html/wp-admin/admin.php(259): do_action()
#26 {main}"

**Comment by jensschuppe** [comment]
Fixed in `1.0-beta11` and `1.1-alpha8`.
