### ISSUE TITLE
Deleting a custom field doesn't remove it from the FB form

### ISSUE THREAD

**Issue by MegaphoneJon** [systopia/de.systopia.eck#139]
If you delete a custom field associated with an entity, it still appears on the FormBuilder form, which causes the form to stop working.

**Comment by colemanw** [comment]
I think we could simplify the code in ECK to use the new [automatic custom blocks](https://github.com/civicrm/civicrm-core/pull/30239) instead of generating the field markup ourselves.

**Comment by jensschuppe** [comment]
Something like this #140 @colemanw?
