### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by colemanw** [systopia/de.systopia.eck#2]
I'd like to contribute. I think we could streamline some of the code and push up some small patches to `civicrm-core` to make the virtual DAOs work better.
However, I'm not able to create a branch, and forking is disabled, so I'm unable to open pull-requests.

**Comment by jensschuppe** [comment]
The repository is now public. Happy to hear you want to take on this again, @colemanw! Let us know if/when you'd like to discuss things. There's also a first draft of docs available now because there's not a UI for everything yet, especially creating entities of custom entity types.
