### ISSUE TITLE
Unique constraint on optionValues

### ISSUE THREAD

**Issue by colemanw** [systopia/de.systopia.eck#27]
The APIv4 unit test is currently failing because it attempts to create 2 EckEntityTypes, and then create sub-types for both of them. As part of the test, it gives them both a sub-type of the same name.

That should certainly work; it shouldn't matter if different entities have sub-types with the same name. However, because this extension is re-using a single OptionGroup, a constraint is enforced by CiviCRM core which does not allow OptionValues in the same group to have the same value.

At first I thought it was a core bug and opened up https://github.com/civicrm/civicrm-core/pull/22828, however I looked at how the `grouping` is used in other option groups like Case Status, and in that use-case `grouping` is either "open" or "closed", but regardless of grouping the values still need to be unique.

So I don't think that PR is mergeable, and I think we need to switch this extension to creating a new option group for every Eck entity type. We can use `hook_civicrm_managed` to do it automatically.

**Comment by jensschuppe** [comment]
Too bad, but sounds plausible to go with separate OptionGroups.

**Comment by colemanw** [comment]
I think I made a mistake.
When testing out the ui forms, I discovered that giving a string value for sub-type causes an error, and CiviCRM-core really expects these to be numeric.
So actually, this issue is moot. If we treat `value` like an auto-increment integer, then `name` has no unique constraint.
#29 fixes the test, which was ultimately the only change needed.
