### ISSUE TITLE
Handle UTF-8 characters in ECK entity type and subtype names

### ISSUE THREAD

**Issue by jensschuppe** [systopia/de.systopia.eck#54]
... because otherwise Symfony complains with `Cannot use UTF-8 route patterns without setting the "utf8" option for route "/civicrm/eck/entity/edit/Süperentity/Bädsubtypename/{extra}"`

We should do one of the following:
* Allow routes to contain UTF-8 characters (if that is at all possible with Afform/SearchKit - @colemanw?)
* Validate/transliterate Entity type and subtype names (their labels can still contain UTF-8)
* Replace non-ASCII characters with a placeholder (e.g. `_`) in relevant places (entity type name, subtype name)
* Use the sub types' `value` instead of their `name` for *Afform* names and routes

**Comment by colemanw** [comment]
@jensschuppe My vote would be your second option "Validate/transliterate Entity type and subtype names (their labels can still contain UTF-8)" because there is a longstanding convention that machine names should not contain special characters.

**Comment by jensschuppe** [comment]
This has now been resolved by

* restricting entity type names to not contain any special characters
* not restricting sub-type names and using their value for *Afform* routes
