### ISSUE TITLE
Validate ECK entity type names for creating valid MySQL table names - DB Error: Syntax error when upgrading CiviCRM Core - dropping triggers

### ISSUE THREAD

**Issue by jensschuppe** [systopia/de.systopia.eck#69]
When upgrading CiviCRM Core from 5.58 to 5.61, I got this error thrown:

`DROP TRIGGER IF EXISTS civicrm_eck_-extension_before_insert [nativecode=1064 ** You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-extension_before_insert' at line 1]`

Seems `-` is not allowed in trigger names, but the ECK entity table contains one.

**Comment by colemanw** [comment]
@jensschuppe @highfalutin I've done a PR to fix this: #71
