### ISSUE TITLE
CI for unit tests

### ISSUE THREAD

**Issue by colemanw** [systopia/de.systopia.eck#7]
Unit tests are going to be very important for an extension such as this.
SearchKit provides a good model for adding APIv4-based tests in an extension.
I'm pretty sure they can be run without a CI server using GitHub actions.

**Comment by colemanw** [comment]
Some useful discussion here about how to set it up.
Looks like GitHub actions can be used for CI to test each PR:
https://chat.civicrm.org/civicrm/pl/c3f7pcfkxffw7cmt19inpz6oce

**Comment by jensschuppe** [comment]
@bjendres I think you implemented CircleCI somewhere. Would this be an option here and could you set it up?

**Comment by bjendres** [comment]
> @bjendres I think you implemented CircleCI somewhere. Would this be an option here and could you set it up?

sure.

**Comment by bjendres** [comment]
I added CI for the extension, currently in branch ``issue/7``. But it seems that the tests themselves currently fail, see [HERE](https://app.circleci.com/pipelines/github/systopia/de.systopia.eck). @colemanw Could you have a quick look at that?

**Comment by bjendres** [comment]
Error seems to be
```
Call to undefined method api\v4\EckEntity\EckEntityTest::assertStringContainsString()
```

**Comment by bjendres** [comment]
Never mind, it just required ``phpunit8``

**Comment by bjendres** [comment]
The test run now gives a "DB Error: unknown error", see [here](https://app.circleci.com/pipelines/github/systopia/de.systopia.eck/3/workflows/0f0a45b3-8360-40eb-8a49-cd10a7533212/jobs/7/tests#failed-test-0). 

@colemanw / @jensschuppe  any idea what could cause this?

**Comment by colemanw** [comment]
Hmm. "unknown error" is not very specific. Are there any other logs or can you enable debugging?

**Comment by bjendres** [comment]
Hm, there's currently only the stack trace:
```
api\v4\EckEntity\EckEntityTest::testCreateEntityType
PEAR_Exception: DB Error: unknown error

/buildkit/build/civi-stable/web/sites/all/modules/civicrm/CRM/Core/Error.php:943
/buildkit/build/civi-stable/web/sites/all/modules/civicrm/vendor/pear/pear-core-minimal/src/PEAR.php:922
/buildkit/build/civi-stable/web/sites/all/modules/civicrm/vendor/pear/db/DB.php:997
/buildkit/build/civi-stable/web/sites/all/modules/civicrm/vendor/pear/pear-core-minimal/src/PEAR.php:575
/buildkit/build/civi-stable/web/sites/all/modules/civicrm/vendor/pear/pear-core-minimal/src/PEAR.php:223
/buildkit/build/civi-stable/web/sites/all/modules/civicrm/vendor/pear/db/DB/common.php:1928
/buildkit/build/civi-stable/web/sites/all/modules/civicrm/vendor/pear/db/DB/mysqli.php:936
/buildkit/build/civi-stable/web/sites/all/modules/civicrm/vendor/pear/db/DB/mysqli.php:406
/buildkit/build/civi-stable/web/sites/all/modules/civicrm/vendor/pear/db/DB/common.php:1234
/buildkit/build/civi-stable/web/sites/all/modules/civicrm/packages/DB/DataObject.php:2696
/buildkit/build/civi-stable/web/sites/all/modules/civicrm/packages/DB/DataObject.php:1245
/buildkit/build/civi-stable/web/sites/all/modules/civicrm/CRM/Core/DAO.php:656
/buildkit/build/civi-stable/web/sites/all/modules/civicrm/CRM/Core/DAO.php:924
/buildkit/build/civi-stable/web/sites/all/modules/civicrm/CRM/Core/DAO.php:940
/buildkit/build/civi-stable/web/sites/all/modules/civicrm/Civi/Api4/Generic/Traits/DAOActionTrait.php:179
/buildkit/build/civi-stable/web/sites/all/modules/civicrm/Civi/Api4/Generic/DAOCreateAction.php:33
/buildkit/build/civi-stable/web/sites/all/modules/civicrm/Civi/Api4/Provider/ActionObjectProvider.php:68
/buildkit/build/civi-stable/web/sites/all/modules/civicrm/Civi/API/Kernel.php:149
/buildkit/build/civi-stable/web/sites/all/modules/civicrm/Civi/Api4/Generic/AbstractAction.php:234
/buildkit/build/civi-stable/web/sites/default/files/civicrm/ext/de.systopia.eck/tests/phpunit/api/v4/EckEntity/EckEntityTest.php:24
/buildkit/extern/phpunit8/phpunit8.phar:671
```
So it seems to be coming from [HERE](https://github.com/systopia/de.systopia.eck/blob/bdb967de238b2694b3a589b9ab54d6548eb11176/tests/phpunit/api/v4/EckEntity/EckEntityTest.php#L24)

**Comment by bjendres** [comment]
You don't get this issue on a freshly built(kit)ed civicrm?

**Comment by colemanw** [comment]
No on a fresh install of CiviCRM + this extension, all tests are passing.

**Comment by bjendres** [comment]
hm, weird. thanks.

**Comment by colemanw** [comment]
![image](https://user-images.githubusercontent.com/2874912/156587583-cf17f15f-a732-443c-91de-6232f412e11f.png)

**Comment by bjendres** [comment]
Do you let the test suit install the extension, or you did that yourself?

**Comment by colemanw** [comment]
The test suite does it.

**Comment by bjendres** [comment]
Ok, thanks, I'll dig into it.

**Comment by colemanw** [comment]
@bjendres on my latest PRs, the [console output](https://app.circleci.com/pipelines/github/systopia/de.systopia.eck/472/workflows/71401bbc-3ab9-46d7-a4c9-969c2169b12e/jobs/473) suggests a conflict in the composer version required:

![image](https://github.com/systopia/de.systopia.eck/assets/2874912/b0c3961a-33c5-46ce-9a99-0e9ec8a9217b)

Perhaps that's an easy fix and we can finally have CI for this extension?

**Comment by bjendres** [comment]
I changed the composer version to 2 with https://github.com/systopia/de.systopia.eck/commit/ccdae3853443346dd030e3cb67faf5ee2313d01a and now the tests seem to pass:
```
PHPUnit 9.5.21 #StandWithUkraine

Warning:       Your XML configuration validates against a deprecated schema.
Suggestion:    Migrate your XML configuration using "--migrate-configuration"!

Installing mastertest_b3y8s schema
....                                                                4 / 4 (100%)

Time: 00:08.341, Memory: 89.00 MB

OK (4 tests, 44 assertions)
```

@colemanw Can we close here or did I overlook something?

**Comment by jensschuppe** [comment]
This seems to be fixed.
