### ISSUE TITLE
"New subtype" button invisible when the entity type form is in a modal

### ISSUE THREAD

**Issue by jensschuppe** [systopia/de.systopia.eck#74]
![invisible-button](https://github.com/systopia/de.systopia.eck/assets/29565644/2a5da0e2-a718-4a63-b485-8f492b8305f2)

**Comment by jensschuppe** [comment]
:facepalm: I didn't notice there are buttons below the form, you're right. Kind of debatable whether that makes sense for *all* buttons, but well ...

**Comment by colemanw** [comment]
@jensschuppe thanks for putting out a new release :)
