### ISSUE TITLE
ECK entities do not have a "dao" property in Entity.get API results

### ISSUE THREAD

**Issue by jensschuppe** [systopia/de.systopia.eck#75]
... making ECK entities incompatible with e. g. *SearchKit*'s JOINs, see civicrm/civicrm-core#26192

* relevant `Entity.get` in https://github.com/civicrm/civicrm-core/blob/dc7bb4a899ea74044df0b8afd8a43b027da40732/ext/search_kit/Civi/Search/Admin.php#L133-L139
* relevant "dao" property switch in https://github.com/civicrm/civicrm-core/blob/dc7bb4a899ea74044df0b8afd8a43b027da40732/ext/search_kit/Civi/Search/Admin.php#L270
* code not accessed due to this issue: https://github.com/civicrm/civicrm-core/blob/dc7bb4a899ea74044df0b8afd8a43b027da40732/ext/search_kit/Civi/Search/Admin.php#L374-L391

Steps to reproduce:
1. Create an ECK entity type
2. Add an *Entity Reference* custom field to it
3. Apply civicrm/civicrm-core#26192
4. Create a *SearchKit* search for the ECK entity
5. Try to add a JOIN for the entity type referenced in the custom field - it won't be available for joining

**Comment by colemanw** [comment]
@jensschuppe sounds like you've thoroughly researched this. Did you have a question about how to solve it?

**Comment by jensschuppe** [comment]
I actually stopped researching due to time issues and just wanted to document my findings. I couldn't find out where the `dao` field is being added to the `Entity.get` result so I don't know what's missing for ECK. I suppose there's some mechanism trying to derive DAO classes from API entity names which fails due to ECK entities sharing a DAO class.

Any hints appreciated though, @colemanw. I added steps to reproduce to the issue summary.

**Comment by colemanw** [comment]
Ok @jensschuppe I thought you had already deduced that adding 'dao' to the metadata fixes the problem. Here is [a PR to do that](https://github.com/systopia/de.systopia.eck/pull/78), it certainly appears to fix it in my testing. Am I missing something?

**Comment by jensschuppe** [comment]
Oh really, is it that simple, just adding it to the metadata? Thanks, that indeed makes it work!
