### ISSUE TITLE
"Custom Entities" navigation menu item is shown to users that don't have permission to manage custom entities

### ISSUE THREAD

**Issue by angusfretwell** [systopia/de.systopia.eck#96]
Currently the menu item is shown to all users. My understanding is that until per-entity permissions are implemented, only users that can administer CiviCRM can view/edit custom entities.

I think it'd make sense to change the permissions of the menu item to align with the permissions of the entities (i.e., if my assumption about entity permissions is correct, change the permission on the menu item to `administer CiviCRM`). If not, would it be possible to surface the menu items under `civicrm/admin/menu` so that they can be customised?

I'm happy to submit a PR – just wanted to clarify the approach first 😄

**Comment by jensschuppe** [comment]
Thanks for your input.

(This made me realise that the permission for administering subtypes has always been *access CiviCRM* when it should have been *administer CiviCRM* - see #97)

First, there's administration of ECK entity types (and subtypes), which is (or should be, see above) allowed for admins only, those are the paths starting with `/civicrm/admin/eck/`.

I guess you're referring to the listings, single views and edit forms for individual entities of those types (paths starting with `/civicrm/eck/`. They're currently granted access for all users with the *access CiviCRM* permission (basically all CiviCRM users). We did not want to require admin permissions for actually using those entities, as they're considered "content", just as contacts, activities, etc. are. The missing permissions are the reason though why we do not want to ship a beta version without them (see #34 and #51).

So, I'm afraid the approach you described differs from what we've been planning so far.

We also chose not to put the listings menu item inside an existing submenu, as it's too generic to fit into any.

I took the chance to convert navigation menu items definition to managed entities which apparently makes the top-level menu item available in the navigation menu administration UI for moving it around.

If you're still interested in providing a PR for permissions as described in the other issues, feel free to do so.
