### ISSUE TITLE
No buttons displayed on navigation to ECK 

### ISSUE THREAD

**Issue by gzh1960** [systopia/de.systopia.eck#99]
Hi just wondering if I am doing something wrong as I cannot see any buttons on the ECK screen.
CiviCRM 5.67.1
MySQL8
Wordpress 6.4.1

Downloaded latest extension from github.

The screen displays and seems to try and display a second screen below it (which I think might be the subtype form?)

![image](https://github.com/systopia/de.systopia.eck/assets/6695874/d116e723-a387-4b54-af4a-99459f604924)

Any ideas are welcomed!

**Comment by jensschuppe** [comment]
Thanks for reporting, @gzh1960!

The table is a *SearchKit* display which would list existing ECK entity types along with buttons for operations and an "Add ECK Entity Type" button above it.

Could you check JS errors in the browser's console?

**Comment by gzh1960** [comment]
Getting a https 500 error
https://myurl/wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fajax%2Fapi4

**Comment by gzh1960** [comment]
Error log for website:
www.mysite... [Wed Nov 29 16:31:02 2023] [error] [pid 44759] mod_cgid.c(1079): [client 91.134.126.91:0] AH01264: script not found or unable to stat: /home/mysite/www/www/inputs.php


CiviCRM lo
2023-11-28 12:44:48+1100  [error] 
$Fatal Error Details = array:3 [
  "message" => "No ECK entity type given."
  "code" => null
  "exception" => CRM_Core_Exception {#1741
    #message: "No ECK entity type given."
    #code: 0
    #file: "/home/mysite/www/test/wp-content/uploads/civicrm/ext/de.systopia.eck-master/de.systopia.eck-master/CRM/Eck/Page/Entity.php"
    #line: 47
    #cause: null
    -_trace: null
    -errorData: array:1 [
      "error_code" => 0
    ]
    trace: {
      /home/mysite/www/test/wp-content/uploads/civicrm/ext/de.systopia.eck-master/de.systopia.eck-master/CRM/Eck/Page/Entity.php:47 {
        CRM_Eck_Page_Entity->run()
        › if (!$entity_type_name = CRM_Utils_Request::retrieve('type', 'String', $this)) {
        ›   throw new CRM_Core_Exception('No ECK entity type given.');
        › }
      }
      /home/mysite/www/test/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php:322 { …}
      /home/mysite/www/test/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php:69 { …}
      /home/mysite/www/test/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php:36 { …}
      /home/mysite/www/test/wp-content/plugins/civicrm/civicrm.php:1199 { …}
      /home/mysite/www/test/wp-includes/class-wp-hook.php:324 { …}
      /home/mysite/www/test/wp-includes/class-wp-hook.php:348 { …}
      /home/mysite/www/test/wp-includes/plugin.php:517 { …}
      /home/mysite/www/test/wp-admin/admin.php:259 { …}
    }
  }
]


2023-11-28 12:44:48+1100  [debug] $backTrace = #0 /home/mysite/www/test/wp-content/plugins/civicrm/civicrm/CRM/Core/Error.php(443): CRM_Core_Error::backtrace("backTrace", TRUE)
#1 /home/mysite/www/test/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(39): CRM_Core_Error::handleUnhandledException(Object(CRM_Core_Exception))
#2 /home/mysite/www/test/wp-content/plugins/civicrm/civicrm.php(1199): CRM_Core_Invoke::invoke((Array:3))
#3 /home/mysite/www/test/wp-includes/class-wp-hook.php(324): CiviCRM_For_WordPress->invoke("")
#4 /home/mysite/www/test/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters("", (Array:1))
#5 /home/mysite/www/test/wp-includes/plugin.php(517): WP_Hook->do_action((Array:1))
#6 /home/mysite/www/test/wp-admin/admin.php(259): do_action("toplevel_page_CiviCRM")
#7 {main}

**Comment by gzh1960** [comment]
Response body JSON:
XHRPOST
https://test.mysite.com/wp-admin/admin.php?page=CiviCRM&q=civicrm/ajax/api4
[HTTP/2 500  227ms]

	
run	Object { error_code: 0, error_message: "DB Error: unknown error", status: 500 }
error_code	0
error_message	"DB Error: unknown error"
status	500

**Comment by jensschuppe** [comment]
The CiviCRM log entry does not correspond to that page. Have you tried to clear caches and rebuild the menu router?

**Comment by gzh1960** [comment]
Thanks, but in the Civi log it is showing an error from the extension.

I have tried clearing Civi cache and restarted page but to no avail, same error.

**Comment by jensschuppe** [comment]
The file `CRM/Eck/Page/Entity.php` contains the controller for the path `/civicrm/eck/entity`, which is a different page than the one you provided a screenshot of.

Unfortunately I'm not using WordPress, so I can't replicate the error. Maybe clearing the CMS cache will help …?

**Comment by colemanw** [comment]
> Has this extension been tested using Wordpress?

Yes, I've got it running on WP right now. I just tried a fresh build of:

- WP 6.2 (I'm behind you but I don't think it matters)
- Civi 5.67.2 (also probably not a big deal but you are one point behind the latest release)
- MySql 8.0.29

And this is what I see when I freshly install ECK and visit **Administer -> Customize Data & Screens -> ECK Entity Types** in the menubar:

![image](https://github.com/systopia/de.systopia.eck/assets/2874912/15b6f479-62d8-49a9-92d5-8c7a5d0546da)

I see that the SearchKit display itself is working for you, but when it tries to load data it gets `DB Error` back from the server. That's pretty vague, but last time I saw that error it was a database collation issue. Can you check your default DB collation? ECK seems to be pretty sensitive to this, and I've seen errors when the DB is not set to `COLLATE utf8mb4_unicode_ci`.

**Comment by hershelsr** [comment]
There were a few tables, but I fixed those:

```
ALTER TABLE `civicrm_fountaintribe_yahrzeits_temp` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `civicrm_install_canary` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `civicrm_search_display` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `civicrm_search_segment` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
```

When we load /wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fadmin%2Feck%2Fentity-types the last Ajax call to /wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fajax%2Fapi4 returns

`{"run":{"error_code":0,"error_message":"DB Error: unknown error","status":500}}`

Debugging and Backtrace are enabled.

**Comment by gzh1960** [comment]
Thanks Coleman and Hershel for your help.
I have run the following in phpMyAdmin after checking your discoveries as the following tables for some reason were set to other collations, not sure how or why.

ALTER TABLE `wp_commentmeta` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
AlTER TABLE `wp_comments` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_links` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_options` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_postmeta` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_posts` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_termmeta` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_terms` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_term_relationships` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_term_taxonomy` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_usermeta` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_users` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `civicrm_eck_entity_type` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `civicrm_eck_gh` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `civicrm_eck_ghtest2` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `civicrm_afform_submission` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

Cleared cache, logged out, clear browser cache too!
Retested and get the same result.

Checked ConfigAndLog and it shows the following:
2023-11-29 22:36:15+1100  [debug] SECURITY ALERT: Ajax requests can only be issued by javascript clients, eg. CRM.api4().
Array
(
    [IP] => 14.200.79.12
    [level] => security
    [referer] => 
    [reason] => CSRF suspected
)

Help thoughts (whisky?)

**Comment by gzh1960** [comment]
The whisky helped!
S U C C E S S !  ! !

I inspected the table structure in phpMyAdmin and found the Collation value at the field level definition was set to something else other than utf8mb4_unicode_ci. 
Modified those fields Collation and it is working now.
Thanks all for your assistance with this one!

**Comment by colemanw** [comment]
@gzh1960 I recommend you change the collation of your *database*. That ensures that any new tables will get the correct collation, otherwise new tables will keep getting created with the wrong collation (adding an ECK entity will add a new table, so do it before you do that).

**Comment by gzh1960** [comment]
So I added an entity type OfficeEquipment and then added a subtype Screens, created 2 custom fields and then went to add the data but  received the following messages:
![image](https://github.com/systopia/de.systopia.eck/assets/6695874/595327fe-1386-46df-b9d6-0d09a30c4d8b)
and then clicked add officeequipment and subtype of screens and received 
![image](https://github.com/systopia/de.systopia.eck/assets/6695874/745897b0-496d-4897-82c1-c0830dc603da)

In phpMyAdmin found the table generated has two fields which were set to utf8mb3_unicode_ci instead of utf8mb4_unicode_ci. Don't know how it managed to do this?
Also the table created had collation set to utf8mb3_unicode_ci. Again how is it doing this? Where is it getting this from?

Tried a second example and got the same results. Help please?

**Comment by gzh1960** [comment]
CiviCRM ConfigAndLog:

2023-11-30 11:11:01+1100  [error] 
$Fatal Error Details = array:3 [
  "message" => "No ECK entity type given."
  "code" => null
  "exception" => CRM_Core_Exception {#1923
    #message: "No ECK entity type given."
    #code: 0
    #file: "/home/cremorne/www/test/wp-content/uploads/civicrm/ext/de.systopia.eck-master/de.systopia.eck-master/CRM/Eck/Page/Entity.php"
    #line: 47
    #cause: null
    -_trace: null
    -errorData: array:1 [
      "error_code" => 0
    ]
    trace: {
      /home/cremorne/www/test/wp-content/uploads/civicrm/ext/de.systopia.eck-master/de.systopia.eck-master/CRM/Eck/Page/Entity.php:47 {
        CRM_Eck_Page_Entity->run()
        › if (!$entity_type_name = CRM_Utils_Request::retrieve('type', 'String', $this)) {
        ›   throw new CRM_Core_Exception('No ECK entity type given.');
        › }
      }
      /home/cremorne/www/test/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php:322 { …}
      /home/cremorne/www/test/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php:69 { …}
      /home/cremorne/www/test/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php:36 { …}
      /home/cremorne/www/test/wp-content/plugins/civicrm/civicrm.php:1199 { …}
      /home/cremorne/www/test/wp-includes/class-wp-hook.php:324 { …}
      /home/cremorne/www/test/wp-includes/class-wp-hook.php:348 { …}
      /home/cremorne/www/test/wp-includes/plugin.php:517 { …}
      /home/cremorne/www/test/wp-admin/admin.php:259 { …}
    }
  }
]


2023-11-30 11:11:01+1100  [debug] $backTrace = #0 /home/cremorne/www/test/wp-content/plugins/civicrm/civicrm/CRM/Core/Error.php(443): CRM_Core_Error::backtrace("backTrace", TRUE)
#1 /home/cremorne/www/test/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(39): CRM_Core_Error::handleUnhandledException(Object(CRM_Core_Exception))
#2 /home/cremorne/www/test/wp-content/plugins/civicrm/civicrm.php(1199): CRM_Core_Invoke::invoke((Array:6))
#3 /home/cremorne/www/test/wp-includes/class-wp-hook.php(324): CiviCRM_For_WordPress->invoke("")
#4 /home/cremorne/www/test/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters("", (Array:1))
#5 /home/cremorne/www/test/wp-includes/plugin.php(517): WP_Hook->do_action((Array:1))
#6 /home/cremorne/www/test/wp-admin/admin.php(259): do_action("toplevel_page_CiviCRM")
#7 {main}

**Comment by colemanw** [comment]
> A further question: I have a table created by a scheduled job in CiviCRM and I want to use Searchkit to query it, hence the interest in this extension. Is this extension going to help me with this goal?

I'm not fully sure I understand what you mean. If you create the table via ECK then yes you can use custom code to populate it with a scheduled job and SearchKit will be able to query it.
However, if your table is unrelated to ECK then this extension isn't going to do anything for you. It exists to create and manage ECK tables and expose them to FormBuilder and SearchKit and APIv4.

**Comment by gzh1960** [comment]
> > A further question: I have a table created by a scheduled job in CiviCRM and I want to use Searchkit to query it, hence the interest in this extension. Is this extension going to help me with this goal?
> 
> I'm not fully sure I understand what you mean. If you create the table via ECK then yes you can use custom code to populate it with a scheduled job and SearchKit will be able to query it. However, if your table is unrelated to ECK then this extension isn't going to do anything for you. It exists to create and manage ECK tables and expose them to FormBuilder and SearchKit and APIv4.

Thank you I think you have answered my question. The requirement was to be able to use Searchkit to report and action the data created by a scheduled job which is run regularly. This table is not ECK created so this is a problem.
It creates a specific table outside of ECK and I was hoping this extension would allow me to query it. So the $64 question is do you think this functionality could be incorporated somehow into CiviCRM via Searchkit or this extension???

**Comment by gzh1960** [comment]
Thank you all for your help. The database and setup were converted to the correct collation and I have been able to add records to a sample Entity with success. Have run a report using Searchkit and it all works nicely now. Great work all!

Coleman: I am thinking maybe I could create the Entity using ECK with the same table definitions that my process from the scheduled job creates and then copying the data from the scheduled job into the ECK table. Hopefully then I can report using Searchkit and continue the business process required. What do you think? Any catches?
